### ISSUE TITLE
ssdeep_fuzzy_hash_compare() in the docs should be ssdeep_fuzzy_compare()

### ISSUE THREAD

**Issue by mmaunder** [treffynnon/lib_mysqludf_ssdeep#2]
Function has incorrect name in the README.markdown file.

**Comment by treffynnon** [comment]
Thank you for identifying this error. Fix in commit 935fa52b0a2e3eb2c2919ed71516416bc91a670e

**Comment by mmaunder** [comment]
Awesome!
